/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurent_02;

import java.awt.Color;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author USER
 */
public class log_in extends javax.swing.JFrame {

    /**
     * Creates new form log_in
     */
    int x,y;
    static String name1="0",num1="0";
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    static String rs_chk="0";
    
    public log_in(){
        initComponents();
        database_connect();
    }
    
     public final void database_connect(){
        try{
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurent","root","root"); 
        } 
        catch (SQLException ex){
            Logger.getLogger(ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        login_right = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        login_password = new javax.swing.JPasswordField();
        login_id = new javax.swing.JTextField();
        ckbox_psw = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sign_up_button = new javax.swing.JButton();
        login_button1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        log_in_bar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        login_left = new keeptoo.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 650));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(241, 227, 254));
        jPanel1.setForeground(new java.awt.Color(255, 229, 165));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(1090, 30, 10, 620);

        login_right.setBackground(new java.awt.Color(255, 255, 255));
        login_right.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(153, 51, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 255));
        jLabel1.setText("Make your order now");
        login_right.add(jLabel1);
        jLabel1.setBounds(70, 130, 250, 50);

        login_password.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        login_password.setForeground(new java.awt.Color(153, 153, 153));
        login_password.setText("Password");
        login_password.setBorder(null);
        login_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                login_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                login_passwordFocusLost(evt);
            }
        });
        login_right.add(login_password);
        login_password.setBounds(120, 300, 200, 40);

        login_id.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        login_id.setForeground(new java.awt.Color(153, 153, 153));
        login_id.setText("Number");
        login_id.setBorder(null);
        login_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                login_idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                login_idFocusLost(evt);
            }
        });
        login_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_idActionPerformed(evt);
            }
        });
        login_right.add(login_id);
        login_id.setBounds(120, 230, 200, 40);

        ckbox_psw.setBackground(new java.awt.Color(255, 255, 255));
        ckbox_psw.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ckbox_psw.setForeground(new java.awt.Color(204, 102, 255));
        ckbox_psw.setText("show password");
        ckbox_psw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbox_pswActionPerformed(evt);
            }
        });
        login_right.add(ckbox_psw);
        ckbox_psw.setBounds(250, 360, 140, 24);

        jSeparator1.setForeground(new java.awt.Color(204, 51, 255));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        login_right.add(jSeparator1);
        jSeparator1.setBounds(120, 340, 200, 20);

        jSeparator2.setForeground(new java.awt.Color(204, 51, 255));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        login_right.add(jSeparator2);
        jSeparator2.setBounds(120, 270, 200, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8_account_30px.png"))); // NOI18N
        login_right.add(jLabel2);
        jLabel2.setBounds(60, 240, 40, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8_password_32px.png"))); // NOI18N
        login_right.add(jLabel3);
        jLabel3.setBounds(60, 310, 30, 30);

        sign_up_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sign_up_button.setForeground(new java.awt.Color(0, 153, 255));
        sign_up_button.setText("Sign up");
        sign_up_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_up_buttonActionPerformed(evt);
            }
        });
        login_right.add(sign_up_button);
        sign_up_button.setBounds(260, 550, 100, 40);

        login_button1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        login_button1.setForeground(new java.awt.Color(153, 0, 255));
        login_button1.setText("Log in");
        login_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_button1ActionPerformed(evt);
            }
        });
        login_right.add(login_button1);
        login_button1.setBounds(160, 420, 90, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("Don't have account?");
        login_right.add(jLabel4);
        jLabel4.setBounds(40, 540, 160, 40);

        getContentPane().add(login_right);
        login_right.setBounds(700, 30, 390, 610);

        log_in_bar.setBackground(new java.awt.Color(255, 0, 51));
        log_in_bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                log_in_barMouseDragged(evt);
            }
        });
        log_in_bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                log_in_barMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                log_in_barMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                log_in_barMousePressed(evt);
            }
        });
        log_in_bar.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        log_in_bar.add(jLabel6);
        jLabel6.setBounds(1070, 0, 20, 30);

        getContentPane().add(log_in_bar);
        log_in_bar.setBounds(0, 0, 1100, 30);

        login_left.setkEndColor(new java.awt.Color(255, 255, 255));
        login_left.setkStartColor(new java.awt.Color(255, 153, 102));
        login_left.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/food_01.png"))); // NOI18N
        login_left.add(jLabel5);
        jLabel5.setBounds(50, 190, 570, 400);

        jPanel4.setBackground(new java.awt.Color(102, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setForeground(new java.awt.Color(255, 153, 0));
        jPanel4.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Atik's Cloud Kitchen");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(30, 10, 460, 60);

        login_left.add(jPanel4);
        jPanel4.setBounds(130, 60, 510, 90);

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setForeground(new java.awt.Color(255, 153, 0));
        jPanel3.setLayout(null);
        login_left.add(jPanel3);
        jPanel3.setBounds(360, 0, 40, 60);

        getContentPane().add(login_left);
        login_left.setBounds(0, 30, 700, 610);

        jPanel2.setBackground(new java.awt.Color(241, 227, 254));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 640, 1090, 10);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void log_in_barMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_in_barMouseEntered
        // TODO add your handling code here:
        log_in_bar.setBackground(new Color(204,0,0));
    }//GEN-LAST:event_log_in_barMouseEntered

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        //System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void log_in_barMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_in_barMouseExited
        // TODO add your handling code here:
        log_in_bar.setBackground(new Color(255,0,51));
    }//GEN-LAST:event_log_in_barMouseExited

    private void log_in_barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_in_barMouseDragged
        // TODO add your handling code here:
        int xx=evt.getXOnScreen();
        int yy=evt.getYOnScreen();
        this.setLocation(xx-x,yy-y);
    }//GEN-LAST:event_log_in_barMouseDragged

    private void log_in_barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_in_barMousePressed
        // TODO add your handling code here:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_log_in_barMousePressed

    private void login_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_idActionPerformed

    private void login_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_idFocusGained
        // TODO add your handling code here:
        if(login_id.getText().equals("Number")){
            login_id.setText("");
            login_id.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_login_idFocusGained

    private void login_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_idFocusLost
        // TODO add your handling code here:
         if(login_id.getText().equals("")){
            login_id.setText("Number");
            login_id.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_login_idFocusLost

    private void ckbox_pswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbox_pswActionPerformed
        // TODO add your handling code here:
        if(ckbox_psw.isSelected()){
            login_password.setEchoChar((char)0);
        }
        else{
            login_password.setEchoChar('*');
        }
    }//GEN-LAST:event_ckbox_pswActionPerformed

    private void login_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_passwordFocusGained
        // TODO add your handling code here:
        if(login_password.getText().equals("Password")){
            login_password.setText("");
            login_password.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_login_passwordFocusGained

    private void login_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_passwordFocusLost
        // TODO add your handling code here:
        if(login_password.getText().equals("")){
            login_password.setText("Password");
            login_password.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_login_passwordFocusLost

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MousePressed

    private void login_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_button1ActionPerformed
        String num, pass, pa = "";
        num = login_id.getText();
        pass = login_password.getText();
        if(num.equals("") || num.equals("Number")){
            JOptionPane.showMessageDialog(null, "Please Enter Username!!!");
        }
        else if(pass.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter Password!!!");
        }
        else if(num.equals("admin") && pass.equals("admin")){
            Admin_panel_01 adm=new Admin_panel_01();
            adm.setVisible(true);
            dispose();
        }
        else{
            try{
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurent","root","root");
                String sql = "Select *from login where number = '"+num+"'";
                pst = c.prepareStatement(sql);
                
                rs = pst.executeQuery();
                if(rs.next()){
                    pa = rs.getString(3);
                    name1=rs.getString(1);
                    num1=rs.getString(2);
                    rs.close();
                    c.close();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Incorrect Username!!!");
                }
                if(pass.equals(pa)){
                    //progress_page pg=new progress_page();
                    //pg.show();
                    
                    //call_payment_func();
                    progress_page ui=new progress_page();
                    ui.setVisible(true);
                    dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Incorrect Password!!!");
                }
            }
            catch(SQLException ex){
                Logger.getLogger(ex.getMessage());
            }
        }
    }//GEN-LAST:event_login_button1ActionPerformed

    private void sign_up_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_up_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
        sign_up su=new sign_up();
        su.setVisible(true);
    }//GEN-LAST:event_sign_up_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new log_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ckbox_psw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel log_in_bar;
    private javax.swing.JButton login_button1;
    private javax.swing.JTextField login_id;
    private keeptoo.KGradientPanel login_left;
    private javax.swing.JPasswordField login_password;
    private javax.swing.JPanel login_right;
    private javax.swing.JButton sign_up_button;
    // End of variables declaration//GEN-END:variables
}
