/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurent_02;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class multiple_restaurent extends javax.swing.JFrame {

    /**
     * Creates new form log_in
     */
    int x,y;
    public multiple_restaurent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        log_in_bar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        login_left = new keeptoo.KGradientPanel();
        login_right = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        restaurent_01 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        restaurent_02 = new keeptoo.KGradientPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(930, 650));
        setUndecorated(true);
        getContentPane().setLayout(null);

        log_in_bar.setBackground(new java.awt.Color(0, 153, 204));
        log_in_bar.setMinimumSize(new java.awt.Dimension(900, 30));
        log_in_bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                log_in_barMouseDragged(evt);
            }
        });
        log_in_bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                log_in_barMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                log_in_barMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                log_in_barMousePressed(evt);
            }
        });
        log_in_bar.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        log_in_bar.add(jLabel6);
        jLabel6.setBounds(890, 0, 20, 30);

        getContentPane().add(log_in_bar);
        log_in_bar.setBounds(0, 0, 930, 30);

        login_left.setkEndColor(new java.awt.Color(153, 102, 255));
        login_left.setkStartColor(new java.awt.Color(0, 153, 204));
        login_left.setLayout(null);

        login_right.setBackground(new java.awt.Color(255, 255, 255));
        login_right.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Choose Restaurent");
        login_right.add(jLabel1);
        jLabel1.setBounds(280, 70, 280, 50);

        kGradientPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 153), 1, true));
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 204, 153));
        kGradientPanel2.setkGradientFocus(1500);
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 51));
        jLabel3.setText("Not Available !");
        kGradientPanel2.add(jLabel3);
        jLabel3.setBounds(40, 90, 150, 40);

        login_right.add(kGradientPanel2);
        kGradientPanel2.setBounds(570, 190, 220, 210);

        restaurent_01.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 153), 1, true));
        restaurent_01.setkEndColor(new java.awt.Color(255, 204, 153));
        restaurent_01.setkGradientFocus(1500);
        restaurent_01.setkStartColor(new java.awt.Color(255, 255, 255));
        restaurent_01.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                restaurent_01FocusGained(evt);
            }
        });
        restaurent_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restaurent_01MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                restaurent_01MouseEntered(evt);
            }
        });
        restaurent_01.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/rsz_fastfood_res_01.png"))); // NOI18N
        restaurent_01.add(jLabel4);
        jLabel4.setBounds(30, 20, 160, 140);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 51));
        jLabel5.setText("Fast Food Corner");
        restaurent_01.add(jLabel5);
        jLabel5.setBounds(30, 160, 170, 40);

        login_right.add(restaurent_01);
        restaurent_01.setBounds(40, 190, 220, 210);

        restaurent_02.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 153), 1, true));
        restaurent_02.setkEndColor(new java.awt.Color(255, 204, 153));
        restaurent_02.setkGradientFocus(1500);
        restaurent_02.setkStartColor(new java.awt.Color(255, 255, 255));
        restaurent_02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restaurent_02MouseClicked(evt);
            }
        });
        restaurent_02.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/rsz_1kacchi_res_01.png"))); // NOI18N
        restaurent_02.add(jLabel7);
        jLabel7.setBounds(30, 20, 160, 140);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 51));
        jLabel8.setText("Biriyani House");
        restaurent_02.add(jLabel8);
        jLabel8.setBounds(50, 160, 170, 40);

        login_right.add(restaurent_02);
        restaurent_02.setBounds(310, 190, 220, 210);

        login_left.add(login_right);
        login_right.setBounds(40, 0, 830, 550);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        login_left.add(jPanel1);
        jPanel1.setBounds(200, 550, 700, 30);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        login_left.add(jPanel2);
        jPanel2.setBounds(870, 110, 30, 440);

        getContentPane().add(login_left);
        login_left.setBounds(0, 30, 930, 620);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        //System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        // TODO add your handling code here:
        log_in l=new log_in();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MousePressed

    private void restaurent_01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaurent_01MouseClicked
        // TODO add your handling code here
         
        //restaurent_01.setkGradientFocus(2000);
        Application_UI ui=new Application_UI();
        ui.setVisible(true);
        dispose();
    }//GEN-LAST:event_restaurent_01MouseClicked

    private void restaurent_01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaurent_01MouseEntered
        // TODO add your handling code here:
        //restaurent_01.kEndColor(150,150,51);
         restaurent_01.setkGradientFocus(100);
    }//GEN-LAST:event_restaurent_01MouseEntered

    private void log_in_barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_in_barMousePressed
        // TODO add your handling code here:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_log_in_barMousePressed

    private void log_in_barMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_in_barMouseExited
        // TODO add your handling code here:
        log_in_bar.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_log_in_barMouseExited

    private void log_in_barMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_in_barMouseEntered
        // TODO add your handling code here:
        log_in_bar.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_log_in_barMouseEntered

    private void log_in_barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_in_barMouseDragged
        // TODO add your handling code here:
        int xx=evt.getXOnScreen();
        int yy=evt.getYOnScreen();
        this.setLocation(xx-x,yy-y);
    }//GEN-LAST:event_log_in_barMouseDragged

    private void restaurent_02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaurent_02MouseClicked
        // TODO add your handling code here:
        Application_UI__02 ui2=new Application_UI__02();
        ui2.setVisible(true);
        dispose();
    }//GEN-LAST:event_restaurent_02MouseClicked

    private void restaurent_01FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurent_01FocusGained
        // TODO add your handling code here:
        //restaurent_01.setkGradientFocus(100);
       // restaurent_01.setkStartColor(new java.awt.Color(153, 255, 204));
    }//GEN-LAST:event_restaurent_01FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(multiple_restaurent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(multiple_restaurent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(multiple_restaurent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(multiple_restaurent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new multiple_restaurent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JPanel log_in_bar;
    private keeptoo.KGradientPanel login_left;
    private javax.swing.JPanel login_right;
    private keeptoo.KGradientPanel restaurent_01;
    private keeptoo.KGradientPanel restaurent_02;
    // End of variables declaration//GEN-END:variables
}
