/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurent_02;

import java.awt.Color;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static restaurent_02.Application_UI.bills_id;
import static restaurent_02.log_in.num1;
import static restaurent_02.log_in.rs_chk;



public class payment_system extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    int x,y;
    private Object jLabel7;

    
    public payment_system(){
        initComponents();
        database_connect();
        input_data_from_database();
       // set_data_database();
    }
    String methd="Bkash";
    public final void set_data_database(){
        try {
            String trns=user_transaction.getText();
            String sql = "update payment_info set method='"+methd+"',Transaction='"+trns+"' where bill_id = '"+bills_id+"'";
            pst = con.prepareStatement(sql);

            //pst.setString(6,trns);
            //pst.setString(5,methd);
            pst.executeUpdate();
            
        } catch (SQLException ex){
            Logger.getLogger(payment_system.class.getName()).log(Level.SEVERE, null, ex);
        }
        //JOptionPane.showMessageDialog(this, "New Account Created");
    }
    public final void input_data_from_database(){
        try{
            String sql1 = "Select *from payment_info where number = '"+num1+"'";
            pst = con.prepareStatement(sql1);
            rs = pst.executeQuery();
            
            while(rs.next()){
                String name,num,bill_id,bill_amount;
                int serial;
                
                name=rs.getString(1);
                num=rs.getString(2);
                bill_id=rs.getString(3);
                bill_amount=rs.getString(4);
                //serial=rs.getInt(5);
                
                user_name.setText(name);
                user_num.setText(num);
                user_id.setText(bill_id);
                user_billamount.setText(bill_amount);
            }
        }
        catch(SQLException ex){
            Logger.getLogger(Admin_panel_01.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public final void database_connect(){
        try{
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurent","root","root"); 
        } 
        catch (SQLException ex){
            Logger.getLogger(ex.getMessage());
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        log_in_bar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        login_left = new keeptoo.KGradientPanel();
        login_right = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        user_name = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        user_id = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        user_num = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        user_billamount = new javax.swing.JLabel();
        user_transaction = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        admin_pic = new rojerusan.RSLabelImage();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(930, 650));
        setUndecorated(true);
        getContentPane().setLayout(null);

        log_in_bar.setBackground(new java.awt.Color(255, 0, 51));
        log_in_bar.setMinimumSize(new java.awt.Dimension(900, 30));
        log_in_bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                log_in_barMouseDragged(evt);
            }
        });
        log_in_bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                log_in_barMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                log_in_barMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                log_in_barMousePressed(evt);
            }
        });
        log_in_bar.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        log_in_bar.add(jLabel6);
        jLabel6.setBounds(890, 0, 20, 30);

        getContentPane().add(log_in_bar);
        log_in_bar.setBounds(0, 0, 930, 30);

        login_left.setkEndColor(new java.awt.Color(204, 204, 255));
        login_left.setkStartColor(new java.awt.Color(204, 0, 204));
        login_left.setLayout(null);

        login_right.setBackground(new java.awt.Color(255, 255, 255));
        login_right.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 28)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 255));
        jLabel9.setText("Payment Gateway");
        login_right.add(jLabel9);
        jLabel9.setBounds(240, 10, 270, 50);

        user_name.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        user_name.setForeground(new java.awt.Color(255, 51, 51));
        user_name.setText("null");
        login_right.add(user_name);
        user_name.setBounds(210, 100, 260, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 153, 0));
        jLabel11.setText("Name : ");
        login_right.add(jLabel11);
        jLabel11.setBounds(40, 100, 150, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 153, 0));
        jLabel12.setText("Bill Id :");
        login_right.add(jLabel12);
        jLabel12.setBounds(40, 150, 150, 30);

        user_id.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        user_id.setForeground(new java.awt.Color(255, 51, 51));
        user_id.setText("null");
        login_right.add(user_id);
        user_id.setBounds(210, 150, 260, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 153, 0));
        jLabel14.setText("Number :");
        login_right.add(jLabel14);
        jLabel14.setBounds(40, 200, 140, 30);

        user_num.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        user_num.setForeground(new java.awt.Color(255, 51, 51));
        user_num.setText("null");
        login_right.add(user_num);
        user_num.setBounds(210, 200, 260, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("Payment Method :");
        login_right.add(jLabel16);
        jLabel16.setBounds(110, 340, 240, 30);

        user_billamount.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        user_billamount.setForeground(new java.awt.Color(255, 51, 51));
        user_billamount.setText("null");
        login_right.add(user_billamount);
        user_billamount.setBounds(210, 250, 260, 30);

        user_transaction.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        user_transaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_transactionActionPerformed(evt);
            }
        });
        login_right.add(user_transaction);
        user_transaction.setBounds(380, 380, 240, 30);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 153, 0));
        jLabel17.setText("Bill amount :");
        login_right.add(jLabel17);
        jLabel17.setBounds(40, 250, 140, 30);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 0));
        jButton1.setText("Receipt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        login_right.add(jButton1);
        jButton1.setBounds(300, 450, 130, 50);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bkash", "Rocket", "Nagad" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        login_right.add(jComboBox1);
        jComboBox1.setBounds(380, 340, 120, 30);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("Input Transaction Id :");
        login_right.add(jLabel18);
        jLabel18.setBounds(110, 380, 230, 30);

        admin_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/payment_gateway.png"))); // NOI18N
        login_right.add(admin_pic);
        admin_pic.setBounds(470, 60, 260, 240);

        login_left.add(login_right);
        login_right.setBounds(90, 40, 740, 520);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        login_left.add(jPanel1);
        jPanel1.setBounds(450, 560, 410, 30);

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        login_left.add(jPanel2);
        jPanel2.setBounds(830, 260, 30, 300);

        getContentPane().add(login_left);
        login_left.setBounds(0, 30, 930, 620);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void log_in_barMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_in_barMouseEntered
        // TODO add your handling code here:
        log_in_bar.setBackground(new Color(204,0,0));
    }//GEN-LAST:event_log_in_barMouseEntered

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        //System.exit(0);
        //dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void log_in_barMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_in_barMouseExited
        // TODO add your handling code here:
        log_in_bar.setBackground(new Color(255,0,51));
    }//GEN-LAST:event_log_in_barMouseExited

    private void log_in_barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_in_barMouseDragged
        // TODO add your handling code here:
        int xx=evt.getXOnScreen();
        int yy=evt.getYOnScreen();
        this.setLocation(xx-x,yy-y);
    }//GEN-LAST:event_log_in_barMouseDragged

    private void log_in_barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_in_barMousePressed
        // TODO add your handling code here:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_log_in_barMousePressed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        // TODO add your handling code here:
        //log_in l=new log_in();
        //l.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MousePressed

    private void user_transactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_transactionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_transactionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            set_data_database();
            if(rs_chk.equals("1")){
                Application_UI.jTextArea_receipt.print();
            }
            else if(rs_chk.equals("2")){
                Application_UI__02.jTextArea_receipt_2.print();
            }
            //JOptionPane.showMessageDialog(null,"done .........");
            
        } catch (PrinterException ex) {
            Logger.getLogger(payment_system.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        methd=jComboBox1.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payment_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payment_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payment_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payment_system().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSLabelImage admin_pic;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel log_in_bar;
    private keeptoo.KGradientPanel login_left;
    private javax.swing.JPanel login_right;
    private javax.swing.JLabel user_billamount;
    private javax.swing.JLabel user_id;
    private javax.swing.JLabel user_name;
    private javax.swing.JLabel user_num;
    private javax.swing.JTextField user_transaction;
    // End of variables declaration//GEN-END:variables
}
