/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurent_02;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class sign_up extends javax.swing.JFrame {

    /**
     * Creates new form log_in
     */
    int x,y;
    public sign_up() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        log_in_bar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        login_left = new keeptoo.KGradientPanel();
        login_right = new javax.swing.JPanel();
        signup_password = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sign_up_button = new javax.swing.JButton();
        signup_name = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        signup_number = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(930, 650));
        setUndecorated(true);
        getContentPane().setLayout(null);

        log_in_bar.setBackground(new java.awt.Color(255, 0, 51));
        log_in_bar.setMinimumSize(new java.awt.Dimension(900, 30));
        log_in_bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                log_in_barMouseDragged(evt);
            }
        });
        log_in_bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                log_in_barMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                log_in_barMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                log_in_barMousePressed(evt);
            }
        });
        log_in_bar.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        log_in_bar.add(jLabel6);
        jLabel6.setBounds(890, 0, 20, 30);

        getContentPane().add(log_in_bar);
        log_in_bar.setBounds(0, 0, 930, 30);

        login_left.setkEndColor(new java.awt.Color(153, 102, 255));
        login_left.setkStartColor(new java.awt.Color(102, 0, 153));
        login_left.setLayout(null);

        login_right.setBackground(new java.awt.Color(255, 255, 255));
        login_right.setLayout(null);

        signup_password.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        signup_password.setForeground(new java.awt.Color(153, 153, 153));
        signup_password.setText("Password");
        signup_password.setBorder(null);
        signup_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signup_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signup_passwordFocusLost(evt);
            }
        });
        signup_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_passwordActionPerformed(evt);
            }
        });
        login_right.add(signup_password);
        signup_password.setBounds(480, 270, 190, 40);

        jSeparator1.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        login_right.add(jSeparator1);
        jSeparator1.setBounds(480, 310, 190, 20);

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        login_right.add(jSeparator2);
        jSeparator2.setBounds(480, 240, 190, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8_phone_26px.png"))); // NOI18N
        login_right.add(jLabel2);
        jLabel2.setBounds(420, 210, 40, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8_password_32px.png"))); // NOI18N
        login_right.add(jLabel3);
        jLabel3.setBounds(420, 280, 30, 30);

        sign_up_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sign_up_button.setForeground(new java.awt.Color(0, 153, 255));
        sign_up_button.setText("Sign up");
        sign_up_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_up_buttonActionPerformed(evt);
            }
        });
        login_right.add(sign_up_button);
        sign_up_button.setBounds(510, 370, 100, 40);

        signup_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        signup_name.setForeground(new java.awt.Color(153, 153, 153));
        signup_name.setText("Name");
        signup_name.setBorder(null);
        signup_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signup_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signup_nameFocusLost(evt);
            }
        });
        signup_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_nameActionPerformed(evt);
            }
        });
        login_right.add(signup_name);
        signup_name.setBounds(480, 130, 190, 40);

        jSeparator3.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        login_right.add(jSeparator3);
        jSeparator3.setBounds(480, 170, 190, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8_account_30px.png"))); // NOI18N
        login_right.add(jLabel4);
        jLabel4.setBounds(420, 140, 40, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Or sign up using ");
        login_right.add(jLabel1);
        jLabel1.setBounds(420, 460, 140, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/gmail_01.png"))); // NOI18N
        login_right.add(jLabel5);
        jLabel5.setBounds(660, 460, 30, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/fb logo.png"))); // NOI18N
        login_right.add(jLabel7);
        jLabel7.setBounds(600, 460, 40, 40);

        signup_number.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        signup_number.setForeground(new java.awt.Color(153, 153, 153));
        signup_number.setText("Number");
        signup_number.setBorder(null);
        signup_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signup_numberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signup_numberFocusLost(evt);
            }
        });
        signup_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_numberActionPerformed(evt);
            }
        });
        login_right.add(signup_number);
        signup_number.setBounds(480, 200, 190, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/food_signup.png"))); // NOI18N
        login_right.add(jLabel8);
        jLabel8.setBounds(10, 190, 350, 270);

        kGradientPanel1.setkEndColor(new java.awt.Color(153, 0, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 0, 153));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        login_right.add(kGradientPanel1);
        kGradientPanel1.setBounds(260, -10, 60, 70);

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 28)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 255));
        jLabel9.setText("Sign up");
        login_right.add(jLabel9);
        jLabel9.setBounds(340, 30, 140, 50);

        jPanel3.setBackground(new java.awt.Color(242, 230, 254));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        login_right.add(jPanel3);
        jPanel3.setBounds(0, 0, 20, 510);

        login_left.add(login_right);
        login_right.setBounds(90, 40, 740, 510);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        login_left.add(jPanel1);
        jPanel1.setBounds(450, 550, 410, 30);

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        login_left.add(jPanel2);
        jPanel2.setBounds(830, 260, 30, 290);

        getContentPane().add(login_left);
        login_left.setBounds(0, 30, 930, 620);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void log_in_barMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_in_barMouseEntered
        // TODO add your handling code here:
        log_in_bar.setBackground(new Color(204,0,0));
    }//GEN-LAST:event_log_in_barMouseEntered

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        //System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void log_in_barMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_in_barMouseExited
        // TODO add your handling code here:
        log_in_bar.setBackground(new Color(255,0,51));
    }//GEN-LAST:event_log_in_barMouseExited

    private void log_in_barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_in_barMouseDragged
        // TODO add your handling code here:
        int xx=evt.getXOnScreen();
        int yy=evt.getYOnScreen();
        this.setLocation(xx-x,yy-y);
    }//GEN-LAST:event_log_in_barMouseDragged

    private void log_in_barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_in_barMousePressed
        // TODO add your handling code here:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_log_in_barMousePressed

    private void signup_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_passwordActionPerformed

    private void signup_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_passwordFocusLost
        // TODO add your handling code here:
        if(signup_password.getText().equals("")){
            signup_password.setText("Password");
            signup_password.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_signup_passwordFocusLost

    private void signup_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_passwordFocusGained
        // TODO add your handling code here:
        if(signup_password.getText().equals("Password")){
            signup_password.setText("");
            signup_password.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_signup_passwordFocusGained

    private void signup_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_nameFocusGained
        // TODO add your handling code here:
        if(signup_name.getText().equals("Name")){
            signup_name.setText("");
            signup_name.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_signup_nameFocusGained

    private void signup_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_nameFocusLost
        // TODO add your handling code here:
        if(signup_name.getText().equals("")){
            signup_name.setText("Name");
            signup_name.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_signup_nameFocusLost

    private void signup_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_nameActionPerformed

    private void signup_numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_numberFocusGained
        // TODO add your handling code here:
         if(signup_number.getText().equals("Number")){
           signup_number.setText("");
           signup_number.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_signup_numberFocusGained

    private void signup_numberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_numberFocusLost
        // TODO add your handling code here:
        if(signup_number.getText().equals("")){
            signup_number.setText("Number");
            signup_number.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_signup_numberFocusLost

    private void signup_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_numberActionPerformed

    private void sign_up_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_up_buttonActionPerformed
        // TODO add your handling code here:
        String name,num,pass;
        name = signup_name.getText();
        num=signup_number.getText();
        pass=signup_password.getText();
        
        if(name.equals("") || name.equals("Name")){
            JOptionPane.showMessageDialog(null, "Please Enter Name !!!");
        }
        else if(num.equals("") || num.equals("Number")){
            JOptionPane.showMessageDialog(null, "Please Enter Number !!!");
        }
        else if(pass.equals("") || pass.equals("Password")){
            JOptionPane.showMessageDialog(null, "Please Enter Password!!!");
        }
        else{
            try{
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurent","root","root");
                String sql = "insert into login(name,number,password) values(?,?,?)";
                
                PreparedStatement ptst = c.prepareStatement(sql);
                ptst.setString(1,name);
                ptst.setString(2,num);
                ptst.setString(3,pass);
                ptst.executeUpdate();
                JOptionPane.showMessageDialog(this, "New Account Created");
                c.close();
                
                dispose();
            }
            catch(SQLException ex){
                Logger.getLogger(ex.getMessage());
                JOptionPane.showMessageDialog(this, "Account Using Same Username Already Exists!!!");
            }
        }
        log_in l=new log_in();
        l.setVisible(true);
    }//GEN-LAST:event_sign_up_buttonActionPerformed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        // TODO add your handling code here:
        log_in l=new log_in();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JPanel log_in_bar;
    private keeptoo.KGradientPanel login_left;
    private javax.swing.JPanel login_right;
    private javax.swing.JButton sign_up_button;
    private javax.swing.JTextField signup_name;
    private javax.swing.JTextField signup_number;
    private javax.swing.JTextField signup_password;
    // End of variables declaration//GEN-END:variables
}
